### ISSUE TITLE
Fixing ESLint Problems

### ISSUE THREAD

**Issue by PythonCreator27** [gadicc/node-yahoo-finance2#134]
# Fixing ESLint Problems
I get them all of the time in VSCode. Running `npx eslint src/**/*.ts` produces the following:
```
✖ 55 problems (32 errors, 23 warnings)
  8 errors and 0 warnings potentially fixable with the `--fix` option.
```
55 problems??? Yeah, we need to fix that...

## Checklist
- [ ] Fix ts-ignore issues
- [ ] Remove empty interfaces
- [ ] Remove unneeded type annotations
- [ ] Add missing return types
- [ ] Convert `Function` -> `() => void` 
- [ ] Convert `Object` and `object` to `Record<string, ???>`
- [ ] Use const where possible
- [ ] Convert `require("...")` => `import { ... } from "..."`

**Comment by gadicc** [comment]
Uhh yeah that's my bad, I need to go through all these!  Will get to this after the other issues.  Thanks for raising.
