### ISSUE TITLE
[TESTS] Run each test on multiple symbols and testing using a fixed list of symbols

### ISSUE THREAD

**Issue by PythonCreator27** [gadicc/node-yahoo-finance2#51]
# Running each `it()` block on several symbols
Running each `it()` block on more symbols would definitely increase the accuracy of tests, as certain stocks return some things, and some don't.

## TODO
- [x] Use `it.each()` instead of `testSymbols.forEach()` with  extra `describe` blocks (#53)
- [x] Create some sort of a file that stores a list of symbols to regularly test on (such a file exists)
- [x] Expand the `symbols.ts` file (#58)
- [x] Fix failing CI (after #58 is merged)
- [x] Start using `it.each()` instead of `it()` alone (run tests on multiple symbols) **everywhere** (#63, more coming)

## Benefits
We get added checking of validation, so we don't get things like #46 again. We can also check that the modules work properly for several different symbols.

**Comment by gadicc** [comment]
Hey @PythonCreator27, agree completely.  Thanks for this!

**Comment by PythonCreator27** [comment]
I tried expanding the symbols we use for testing by adding a couple of ones with little data, but unfortunately, the tests are now failing. This is a real issue - more in #57.

**Comment by PythonCreator27** [comment]
Closing as task is done.

**Comment by gadicc** [comment]
Yayyyy :tada: 

Thanks, @PythonCreator27.  As I said in your PR, these were a massive help to me and of course all the other consumers of the library.  So thanks again for all your time and effort here.
